# Generated by Django 6.0 on 2025-12-21 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_title', models.CharField(max_length=500)),
                ('scenes_data', models.JSONField()),
                ('avatar_script', models.TextField()),
                ('avatar_id', models.CharField(max_length=255)),
                ('voice_id', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('avatar_scale', models.FloatField(default=0.8)),
                ('avatar_x', models.FloatField(default=0.7)),
                ('avatar_y', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing_veo', 'processing_veo'), ('processing_heygen', 'processing_heygen'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=32)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('veo_video_gcs_uri', models.CharField(blank=True, max_length=1024)),
                ('veo_video_url', models.URLField(blank=True)),
                ('heygen_video_id', models.CharField(blank=True, max_length=255)),
                ('heygen_asset_id', models.CharField(blank=True, max_length=255)),
                ('final_video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.IntegerField(blank=True, null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='video_gener_user_id_7d163d_idx'), models.Index(fields=['status'], name='video_gener_status_9f6d17_idx')],
            },
        ),
    ]
