# Generated by Django 6.0 on 2025-12-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0002_add_webhook_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='events',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='webhook_url',
        ),
    ]
